project:
  type: website
  output-dir: docs
  
format:
  revealjs:
    code-fold: true
    controls: true
    navigation-mode: linear
    controls-layout: bottom-right
    controls-tutorial: true
    slide-number: true
    show-slide-number: all
    pdfMaxPagesPerSlide: 1
    scrollable: true
    footer: <a href="https://geos270.github.io/">Back</a>
fig-dpi: 300
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true

website:
  title: "Lecture Slides"
  navbar:
    left:
      - href: https://geos270.github.io/
        text: Syllabus
      - href: index.md
        text: Lecture Slides
      - href: https://geos270.github.io/LabAssignments/labs.html
        text: Lab Assignments
  sidebar:
    style: "docked"
    search: true
    contents:    
      - section: "Module 1"
        contents:
        - What_is_GIS/Slides.qmd
        - History_of_GIS/Slides.qmd
        - Modern_GIS/Slides.qmd
      - section: "Module 2"
        contents:
        - Steps_of_Abstraction/Slides.qmd
        - Map_Projections/Slides.qmd
      - section: "Module 3"
        contents:
        - Data_Classification/Slides.qmd
        - Data_Visualization/Slides.qmd
        - Phenomena_and_Data_Types/Slides.qmd
      - section: "Module 4"
        contents:
        - Choice_of_Data_Model/Slides.qmd
        - The_Raster_Data_Model/Slides.qmd
        - Spatial_is_Special/Slides.qmd
        - The_Vector_Data_Model/Slides.qmd
      - section: "Module 5"
        contents:
        - Spatial_Data_Workflows/Slides.qmd
        - Raster_Analysis_Methods/Slides.qmd
        - Vector_Analysis_Methods/Slides.qmd
      - section: "Module 6"
        contents:
        - Ethics_in_GIS/Slides.qmd
        - Spatial_Sampling_Methods/Slides.qmd
        - Uncertainty_in_GIS/Slides.qmd
